openapi: "3.0.3"
info:
  title: "Application API"
  description: "Application API"
  version: "1.0.0"
servers:
  - url: "http://0.0.0.0:8080"
paths:
  /:
    get:
      description: "Hello World!"
      responses:
        "200":
          description: "OK"
          content:
            text/plain:
              schema:
                type: "string"
              examples:
                Example#1:
                  value: "Hello World!"
  /users:
    get:
      description: "Return all users with pagination"
      responses:
        "200":
          description: "OK"
          content:
            application/json:
              schema:
                type: "object"
                properties:
                  data:
                    type: "array"
                    items:
                      $ref: "#/components/schemas/User"
                  metadata:
                    type: "object"
                    properties:
                      total:
                        type: "integer"
                      lastPage:
                        type: "integer"
                      perPage:
                        type: "integer"
components:
  schemas:
    User:
      type: "object"
      properties:
        id:
          type: "string"
          format: uuid
        email:
          type: "string"
        role:
          type: "enum"
          enum:
            - ADMIN
            - CUSTOMER
            - SELLER
        status:
          type: enum
          enum:
            - ACTIVE
            - INACTIVE
        fullName:
          type: string
        createdAt:
          type: string
          format: date-time
        updatedAt:
          type: string
          format: date-time