ktor:
    application:
        modules:
            - example.com.ApplicationKt.module
    deployment:
        port: 8080
postgres:
    url: "jdbc:postgresql://192.168.1.36:5435/sales_db"
    driver: "org.postgresql.Driver"
    user: munipichari
    password: "MDPichari"
