ktor:
    application:
        modules:
            - example.com.ApplicationKt.module
    deployment:
        port: 8080
postgres:
    url: "jdbc:postgresql://localhost:5432/sales_db"
    driver: "org.postgresql.Driver"
    user: postgres
    password: ""
